services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - txt_data:/app/txt_files
    environment:
      FLASK_DEBUG: 1
    command: /bin/sh -c "sleep 10 && flask run -h 0.0.0.0"
    


